### ISSUE TITLE
Latest release on PyPi

### ISSUE THREAD

**Issue by rpotter12** [balasankarc/gemfileparser#7]
@balasankarc Latest version on PyPi is 0.6.2 and latest tag on github is 0.7.0.
Please release the latest tag on PyPi too :)

**Comment by pombredanne** [comment]
@balasankarc if you like we can take over the maintenance of this package (here and/or on gitlab?)
We are adding this as a dependency in scancode with https://github.com/nexB/scancode-toolkit/pull/2075/files and it is important for us that we can get pending issues addressed. We could also fork it as gemfileparser2 otherwise... 
Thank you and please advise!

**Comment by rpotter12** [comment]
@balasankarc ping......
Please add @pombredanne as a maintainer on Pypi too so that he can update Pypi version too :)

**Comment by pombredanne** [comment]
@balasankarc gentle ping :)

**Comment by pombredanne** [comment]
@balasankarc If you cannot grant me PyPI access, please tell us. We will have to switch back to maintaining our fork.

**Comment by pombredanne** [comment]
@balasankarc at this stage, I am going to rename the package to gemfileparser2 so I can upload to PyPI.

**Comment by balasankarc** [comment]
Closing as 0.8.0 is in PyPi - https://pypi.org/project/gemfileparser/0.8.0/
